#!/usr/bin/env bash

DOTFILE_DIR=$(dirname $(readlink --canonicalize --no-newline $0))

cd ~
if [ "$(uname -s)" == "Darwin" ] ; then
    ln -s $DOTFILE_DIR/bash/bashrc .profile
else
    ln -s $DOTFILE_DIR/bash/bashrc .bashrc
fi

mkdir -p .ghc
# ghci doesn't like it if your conf is writable by someone else
cd $DOTFILE_DIR
chmod 755 ghc
chmod 644 ghc/ghci.conf
cd ~/.ghc
ln -s $DOTFILE_DIR/ghc/ghci.conf ghci.conf
cd ~

ln -s $DOTFILE_DIR/git/gitconfig .gitconfig

ln -s $DOTFILE_DIR/hg/hgrc .hgrc

ln -s $DOTFILE_DIR/tmux/tmux.conf .tmux.conf

mkdir -p .vim
ln -s $DOTFILE_DIR/vim/vimrc .vimrc
cd .vim
ln -s $DOTFILE_DIR/vim/autoload autoload
ln -s $DOTFILE_DIR/vim/colors colors
ln -s $DOTFILE_DIR/vim/ftplugin ftplugin
ln -s $DOTFILE_DIR/vim/bundle bundle
cd ~
