""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" General settings
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

syntax on
filetype plugin indent on

colorscheme xoria256

set t_Co=256
set splitright
set ofu=syntaxcomplete#Complete
set ruler

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Filetype settings
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

autocmd bufread,bufnewfile SCons* set ft=python
autocmd bufread,bufnewfile *.scons* set ft=python

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Plugin settings
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

let vimclojure#ParenRainbow=1

call pathogen#infect()

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Key bindings
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

cmap w!! %!sudo tee > /dev/null %

" Add C-o and C-p to mimic `o and `p without insert mode triggered 
nnoremap <silent><C-o> :set paste<CR>m`o<Esc>``:set nopaste<CR>
nnoremap <silent><C-p> :set paste<CR>m`O<Esc>``:set nopaste<CR>
