""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" General settings
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

syntax on
filetype plugin indent on

colorscheme xoria256

" Delete over line breaks and generally behave sanely.
set backspace=2
set cursorline
set foldlevel=99
set foldmethod=syntax
set incsearch
" Always display status line.
set laststatus=2
set nopaste
set ofu=syntaxcomplete#Complete
set ruler
set splitbelow
set splitright
set t_Co=256

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Plugin settings
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

call pathogen#infect()
let g:neocomplete#enable_at_startup = 1
set completeopt-=preview

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Key bindings
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

let mapleader="-"

" For when you open a file without write permission, but you want to write it.
cmap w!! %!sudo tee > /dev/null %
" Go to next search result while in incremental search mode.
cnoremap <C-n> <CR>n/<C-p>

" Tagbar shortcuts
nmap <silent><C-m> :TagbarToggle<CR>
nmap <silent><C-x> :TagbarOpen j<CR>

nmap <silent><C-n> :NERDTreeToggle<CR>

nmap <leader>p :tabn<CR>
nmap <leader>o :tabp<CR>

nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Add C-o and C-p to mimic `o and `p without insert mode triggered 
nmap <silent><C-o> :set paste<CR>m`o<Esc>``:set nopaste<CR>
nmap <silent><C-p> :set paste<CR>m`O<Esc>``:set nopaste<CR>

" Go to tag definition in a vertical tab.
nnoremap <silent><C-]> :vsp<CR><C-]>
