""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" General settings
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

syntax on
filetype plugin indent on

colorscheme xoria256

set cursorline
set incsearch
set nopaste
set ofu=syntaxcomplete#Complete
set ruler
set splitbelow
set splitright
set t_Co=256

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Plugin settings
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

let vimclojure#ParenRainbow=1

call pathogen#infect()

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Key bindings
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

let mapleader="-"

cmap w!! %!sudo tee > /dev/null %
cmap <C-n> <CR>n/<C-p>

nmap <C-m> :TagbarToggle<CR>
nmap <C-l> :NERDTreeToggle<CR>

nmap <leader>p :tabn<CR>
nmap <leader>o :tabp<CR>

" Add C-o and C-p to mimic `o and `p without insert mode triggered 
nnoremap <silent><C-o> :set paste<CR>m`o<Esc>``:set nopaste<CR>
nnoremap <silent><C-p> :set paste<CR>m`O<Esc>``:set nopaste<CR>
